---
sudo: false
language: ruby
cache: bundler
env:
  - COVERALLS_RUN_LOCALLY=true
rvm:
  - 2.5.3
bundler_args: --jobs=2
before_install: gem install bundler -v 1.17.3

script:
  - bundle exec rake spec
  - bundle exec rake rubocop
